appveyor.yml: use VS2017 for x64 builds (fixes #1747)
The version of vcpkg installed with the VS2015 image is too old, but
building a newer version of vcpkg fails despite VS2015 is apparently supported

C:\Tools\vcpkg\toolsrc\include\vcpkg/base/work_queue.h(28): error C2995: 'unknown-type vcpkg::detail::call_moved_action(Action &,const vcpkg::WorkQueue<Action,ThreadLocalData> &,ThreadLocalData &)': function template has already been defined (compiling source file ..\src\vcpkg\base\files.cpp) [C:\Tools\vcpkg\toolsrc\vcpkglib\vcpkglib.vcxproj]
  C:\Tools\vcpkg\toolsrc\include\vcpkg/base/work_queue.h(16): note: see declaration of 'vcpkg::detail::call_moved_action' (compiling source file ..\src\vcpkg\base\files.cpp)